# Social Accounts
social: true
twitter_url: https://twitter.com/gabrielfpro
twitter_handle:
facebook_url: https://www.facebook.com/gabrielferreirapro
github_url: https://github.com/gabrielferreirapro
gitlab_url:
linkedin_url: https://www.linkedin.com/in/gabrielferreirapro
mailto: